### ISSUE TITLE
Add fade transition to the slideshow

### ISSUE THREAD

**Issue by Majoramari** [Redot-Engine/redot-landing-page#61]
Even after merging #60 (I tried the preview), it still flickers black the first time it rolls. Slowing it down and adding a fade transition might make it easier on the eyes. It would also make the glass card look cooler as the image changes with a fade effect. ;)

**Comment by chrisrabe** [comment]
Addressed by PR #97 . This is merged in now

Preview link: https://dev.redotengine.org/

**Comment by chenasraf** [comment]
Maybe I'm understanding this wrong, but the images don't seem to fade transition between them, which imo is really jarring

Is that what OP meant, or should I open a separate issue?

**Comment by Majoramari** [comment]
> Maybe I'm understanding this wrong, but the images don't seem to fade transition between them

No, the issue is still present. I still see the images as black between transitions on the first load, and it feels jumpy because there is no fade. I think it's a bad user experience.

I would have contributed and fixed it myself, but unfortunately, I don't have the time or experience with Nuxt.

**Comment by chenasraf** [comment]
I want to give this a go this week when I have time if no one else beats me to it, if that's okay with the devs
